default: &default
  adapter: postgresql
  database: homes
  username: you
  password: 123456
  host: localhost
  #port: 5000


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: someOtherDB

