


development:
  adapter: postgresql
  encoding: unicode
  database: myapp22
  pool: 5
  username: shaitan
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: myapp11
  pool: 5
  username: shaitan
  password: 123456






