default: &default
  adapter: postgresql
  database: testDB
  username: you
  password: 123456
  host: localhost
  port: 3000


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: someOtherDB